<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class InputForm
#Region "AutoGenerated things"
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.InputGroupBox = New System.Windows.Forms.GroupBox()
        Me.UnavailableGroupBox = New System.Windows.Forms.GroupBox()
        Me.TextBox1 = New System.Windows.Forms.TextBox()
        Me.MonthCalendar1 = New System.Windows.Forms.MonthCalendar()
        Me.SubmitButton = New System.Windows.Forms.Button()
        Me.EndDatePicker = New System.Windows.Forms.DateTimePicker()
        Me.Label3 = New System.Windows.Forms.Label()
        Me.StartDatePicker = New System.Windows.Forms.DateTimePicker()
        Me.Label2 = New System.Windows.Forms.Label()
        Me.ClinicianName = New System.Windows.Forms.TextBox()
        Me.Label1 = New System.Windows.Forms.Label()
        Me.InputGroupBox.SuspendLayout()
        Me.UnavailableGroupBox.SuspendLayout()
        Me.SuspendLayout()
        '
        'InputGroupBox
        '
        Me.InputGroupBox.Controls.Add(Me.UnavailableGroupBox)
        Me.InputGroupBox.Controls.Add(Me.ClinicianName)
        Me.InputGroupBox.Controls.Add(Me.Label1)
        Me.InputGroupBox.Location = New System.Drawing.Point(9, 10)
        Me.InputGroupBox.Margin = New System.Windows.Forms.Padding(2)
        Me.InputGroupBox.Name = "InputGroupBox"
        Me.InputGroupBox.Padding = New System.Windows.Forms.Padding(2)
        Me.InputGroupBox.Size = New System.Drawing.Size(404, 513)
        Me.InputGroupBox.TabIndex = 0
        Me.InputGroupBox.TabStop = False
        '
        'UnavailableGroupBox
        '
        Me.UnavailableGroupBox.Controls.Add(Me.TextBox1)
        Me.UnavailableGroupBox.Controls.Add(Me.MonthCalendar1)
        Me.UnavailableGroupBox.Controls.Add(Me.SubmitButton)
        Me.UnavailableGroupBox.Controls.Add(Me.EndDatePicker)
        Me.UnavailableGroupBox.Controls.Add(Me.Label3)
        Me.UnavailableGroupBox.Controls.Add(Me.StartDatePicker)
        Me.UnavailableGroupBox.Controls.Add(Me.Label2)
        Me.UnavailableGroupBox.Font = New System.Drawing.Font("Microsoft Sans Serif", 10.2!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.UnavailableGroupBox.Location = New System.Drawing.Point(8, 63)
        Me.UnavailableGroupBox.Margin = New System.Windows.Forms.Padding(2)
        Me.UnavailableGroupBox.Name = "UnavailableGroupBox"
        Me.UnavailableGroupBox.Padding = New System.Windows.Forms.Padding(2)
        Me.UnavailableGroupBox.Size = New System.Drawing.Size(391, 446)
        Me.UnavailableGroupBox.TabIndex = 2
        Me.UnavailableGroupBox.TabStop = False
        Me.UnavailableGroupBox.Text = "Time Unavailable"
        '
        'TextBox1
        '
        Me.TextBox1.Location = New System.Drawing.Point(5, 279)
        Me.TextBox1.Multiline = True
        Me.TextBox1.Name = "TextBox1"
        Me.TextBox1.Size = New System.Drawing.Size(372, 117)
        Me.TextBox1.TabIndex = 8
        '
        'MonthCalendar1
        '
        Me.MonthCalendar1.Location = New System.Drawing.Point(77, 96)
        Me.MonthCalendar1.Name = "MonthCalendar1"
        Me.MonthCalendar1.TabIndex = 7
        '
        'SubmitButton
        '
        Me.SubmitButton.Font = New System.Drawing.Font("Microsoft Sans Serif", 10.8!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.SubmitButton.Location = New System.Drawing.Point(5, 401)
        Me.SubmitButton.Margin = New System.Windows.Forms.Padding(2)
        Me.SubmitButton.Name = "SubmitButton"
        Me.SubmitButton.Size = New System.Drawing.Size(372, 41)
        Me.SubmitButton.TabIndex = 5
        Me.SubmitButton.Text = "Submit"
        Me.SubmitButton.UseVisualStyleBackColor = True
        '
        'EndDatePicker
        '
        Me.EndDatePicker.Font = New System.Drawing.Font("Microsoft Sans Serif", 10.8!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.EndDatePicker.Location = New System.Drawing.Point(200, 48)
        Me.EndDatePicker.Margin = New System.Windows.Forms.Padding(2)
        Me.EndDatePicker.Name = "EndDatePicker"
        Me.EndDatePicker.Size = New System.Drawing.Size(181, 24)
        Me.EndDatePicker.TabIndex = 3
        '
        'Label3
        '
        Me.Label3.AutoSize = True
        Me.Label3.Font = New System.Drawing.Font("Microsoft Sans Serif", 10.8!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label3.Location = New System.Drawing.Point(11, 54)
        Me.Label3.Margin = New System.Windows.Forms.Padding(2, 0, 2, 0)
        Me.Label3.Name = "Label3"
        Me.Label3.Size = New System.Drawing.Size(69, 18)
        Me.Label3.TabIndex = 2
        Me.Label3.Text = "End Date"
        '
        'StartDatePicker
        '
        Me.StartDatePicker.Font = New System.Drawing.Font("Microsoft Sans Serif", 10.8!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.StartDatePicker.Location = New System.Drawing.Point(200, 20)
        Me.StartDatePicker.Margin = New System.Windows.Forms.Padding(2)
        Me.StartDatePicker.Name = "StartDatePicker"
        Me.StartDatePicker.Size = New System.Drawing.Size(181, 24)
        Me.StartDatePicker.TabIndex = 1
        '
        'Label2
        '
        Me.Label2.AutoSize = True
        Me.Label2.Font = New System.Drawing.Font("Microsoft Sans Serif", 10.8!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label2.Location = New System.Drawing.Point(6, 26)
        Me.Label2.Margin = New System.Windows.Forms.Padding(2, 0, 2, 0)
        Me.Label2.Name = "Label2"
        Me.Label2.Size = New System.Drawing.Size(74, 18)
        Me.Label2.TabIndex = 0
        Me.Label2.Text = "Start Date"
        '
        'ClinicianName
        '
        Me.ClinicianName.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.ClinicianName.ForeColor = System.Drawing.Color.Black
        Me.ClinicianName.Location = New System.Drawing.Point(172, 18)
        Me.ClinicianName.Margin = New System.Windows.Forms.Padding(2)
        Me.ClinicianName.Name = "ClinicianName"
        Me.ClinicianName.Size = New System.Drawing.Size(228, 26)
        Me.ClinicianName.TabIndex = 1
        '
        'Label1
        '
        Me.Label1.AutoSize = True
        Me.Label1.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label1.Location = New System.Drawing.Point(4, 20)
        Me.Label1.Margin = New System.Windows.Forms.Padding(2, 0, 2, 0)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(124, 20)
        Me.Label1.TabIndex = 0
        Me.Label1.Text = "Clinician's Name"
        '
        'InputForm
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(422, 534)
        Me.Controls.Add(Me.InputGroupBox)
        Me.Margin = New System.Windows.Forms.Padding(2)
        Me.Name = "InputForm"
        Me.Text = "Scheduler Input Form"
        Me.InputGroupBox.ResumeLayout(False)
        Me.InputGroupBox.PerformLayout()
        Me.UnavailableGroupBox.ResumeLayout(False)
        Me.UnavailableGroupBox.PerformLayout()
        Me.ResumeLayout(False)

    End Sub
    Friend WithEvents InputGroupBox As System.Windows.Forms.GroupBox
    Friend WithEvents Label1 As System.Windows.Forms.Label
    Friend WithEvents ClinicianName As System.Windows.Forms.TextBox

    Private Sub Label1_Click(sender As Object, e As EventArgs) Handles Label1.Click

    End Sub
    Friend WithEvents UnavailableGroupBox As System.Windows.Forms.GroupBox
    Friend WithEvents StartDatePicker As System.Windows.Forms.DateTimePicker
    Friend WithEvents Label2 As System.Windows.Forms.Label

    Private Sub DateTimePicker1_ValueChanged(sender As Object, e As EventArgs) Handles StartDatePicker.ValueChanged

    End Sub
    Friend WithEvents EndDatePicker As System.Windows.Forms.DateTimePicker
    Friend WithEvents Label3 As System.Windows.Forms.Label
    Friend WithEvents SubmitButton As System.Windows.Forms.Button
    Friend WithEvents TextBox1 As TextBox
    Friend WithEvents MonthCalendar1 As MonthCalendar


#End Region


End Class
