<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class InputForm
#Region "AutoGenerated things"
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Me.InputGroupBox = New System.Windows.Forms.GroupBox()
        Me.ClinicianNameCombo = New System.Windows.Forms.ComboBox()
        Me.UnavailableGroupBox = New System.Windows.Forms.GroupBox()
        Me.SubmitButton = New System.Windows.Forms.Button()
        Me.EndDatePicker = New System.Windows.Forms.DateTimePicker()
        Me.Label3 = New System.Windows.Forms.Label()
        Me.Label2 = New System.Windows.Forms.Label()
        Me.Label1 = New System.Windows.Forms.Label()
        Me.StartDatePicker = New System.Windows.Forms.DateTimePicker()
        Me.MajorProjMockUPDataSet = New MajorProjectFormMockUp.MajorProjMockUPDataSet()
        Me.MajorProjMockUPDataSetBindingSource = New System.Windows.Forms.BindingSource(Me.components)
        Me.MajorProjMockUPDataSet2 = New MajorProjectFormMockUp.MajorProjMockUPDataSet2()
        Me.NameBindingSource = New System.Windows.Forms.BindingSource(Me.components)
        Me.NameTableAdapter = New MajorProjectFormMockUp.MajorProjMockUPDataSet2TableAdapters.NameTableAdapter()
        Me.DeleteButton = New System.Windows.Forms.Button()
        Me.InputGroupBox.SuspendLayout()
        Me.UnavailableGroupBox.SuspendLayout()
        CType(Me.MajorProjMockUPDataSet, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.MajorProjMockUPDataSetBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.MajorProjMockUPDataSet2, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.NameBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'InputGroupBox
        '
        Me.InputGroupBox.Controls.Add(Me.ClinicianNameCombo)
        Me.InputGroupBox.Controls.Add(Me.UnavailableGroupBox)
        Me.InputGroupBox.Controls.Add(Me.Label1)
        Me.InputGroupBox.Location = New System.Drawing.Point(12, 12)
        Me.InputGroupBox.Name = "InputGroupBox"
        Me.InputGroupBox.Size = New System.Drawing.Size(538, 510)
        Me.InputGroupBox.TabIndex = 0
        Me.InputGroupBox.TabStop = False
        '
        'ClinicianNameCombo
        '
        Me.ClinicianNameCombo.DataSource = Me.NameBindingSource
        Me.ClinicianNameCombo.DisplayMember = "ClinicianName"
        Me.ClinicianNameCombo.Font = New System.Drawing.Font("Microsoft Sans Serif", 10.8!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.ClinicianNameCombo.FormattingEnabled = True
        Me.ClinicianNameCombo.Location = New System.Drawing.Point(277, 25)
        Me.ClinicianNameCombo.Name = "ClinicianNameCombo"
        Me.ClinicianNameCombo.Size = New System.Drawing.Size(240, 30)
        Me.ClinicianNameCombo.TabIndex = 3
        Me.ClinicianNameCombo.ValueMember = "ClinicianName"
        '
        'UnavailableGroupBox
        '
        Me.UnavailableGroupBox.Controls.Add(Me.DeleteButton)
        Me.UnavailableGroupBox.Controls.Add(Me.StartDatePicker)
        Me.UnavailableGroupBox.Controls.Add(Me.SubmitButton)
        Me.UnavailableGroupBox.Controls.Add(Me.EndDatePicker)
        Me.UnavailableGroupBox.Controls.Add(Me.Label3)
        Me.UnavailableGroupBox.Controls.Add(Me.Label2)
        Me.UnavailableGroupBox.Font = New System.Drawing.Font("Microsoft Sans Serif", 10.2!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.UnavailableGroupBox.Location = New System.Drawing.Point(11, 77)
        Me.UnavailableGroupBox.Name = "UnavailableGroupBox"
        Me.UnavailableGroupBox.Size = New System.Drawing.Size(521, 427)
        Me.UnavailableGroupBox.TabIndex = 2
        Me.UnavailableGroupBox.TabStop = False
        Me.UnavailableGroupBox.Text = "Time Unavailable"
        '
        'SubmitButton
        '
        Me.SubmitButton.Font = New System.Drawing.Font("Microsoft Sans Serif", 10.8!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.SubmitButton.Location = New System.Drawing.Point(143, 175)
        Me.SubmitButton.Name = "SubmitButton"
        Me.SubmitButton.Size = New System.Drawing.Size(200, 51)
        Me.SubmitButton.TabIndex = 5
        Me.SubmitButton.Text = "Submit"
        Me.SubmitButton.UseVisualStyleBackColor = True
        '
        'EndDatePicker
        '
        Me.EndDatePicker.Font = New System.Drawing.Font("Microsoft Sans Serif", 10.8!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.EndDatePicker.Location = New System.Drawing.Point(266, 86)
        Me.EndDatePicker.Name = "EndDatePicker"
        Me.EndDatePicker.Size = New System.Drawing.Size(240, 28)
        Me.EndDatePicker.TabIndex = 3
        '
        'Label3
        '
        Me.Label3.AutoSize = True
        Me.Label3.Font = New System.Drawing.Font("Microsoft Sans Serif", 10.8!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label3.Location = New System.Drawing.Point(8, 91)
        Me.Label3.Name = "Label3"
        Me.Label3.Size = New System.Drawing.Size(88, 24)
        Me.Label3.TabIndex = 2
        Me.Label3.Text = "End Date"
        '
        'Label2
        '
        Me.Label2.AutoSize = True
        Me.Label2.Font = New System.Drawing.Font("Microsoft Sans Serif", 10.8!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label2.Location = New System.Drawing.Point(7, 38)
        Me.Label2.Name = "Label2"
        Me.Label2.Size = New System.Drawing.Size(89, 24)
        Me.Label2.TabIndex = 0
        Me.Label2.Text = "Start Date"
        '
        'Label1
        '
        Me.Label1.AutoSize = True
        Me.Label1.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label1.Location = New System.Drawing.Point(6, 25)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(157, 25)
        Me.Label1.TabIndex = 0
        Me.Label1.Text = "Clinician's Name"
        '
        'StartDatePicker
        '
        Me.StartDatePicker.Font = New System.Drawing.Font("Microsoft Sans Serif", 10.8!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.StartDatePicker.Location = New System.Drawing.Point(266, 38)
        Me.StartDatePicker.Name = "StartDatePicker"
        Me.StartDatePicker.Size = New System.Drawing.Size(240, 28)
        Me.StartDatePicker.TabIndex = 6
        '
        'MajorProjMockUPDataSet
        '
        Me.MajorProjMockUPDataSet.DataSetName = "MajorProjMockUPDataSet"
        Me.MajorProjMockUPDataSet.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
        '
        'MajorProjMockUPDataSetBindingSource
        '
        Me.MajorProjMockUPDataSetBindingSource.DataSource = Me.MajorProjMockUPDataSet
        Me.MajorProjMockUPDataSetBindingSource.Position = 0
        '
        'MajorProjMockUPDataSet2
        '
        Me.MajorProjMockUPDataSet2.DataSetName = "MajorProjMockUPDataSet2"
        Me.MajorProjMockUPDataSet2.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
        '
        'NameBindingSource
        '
        Me.NameBindingSource.DataMember = "Name"
        Me.NameBindingSource.DataSource = Me.MajorProjMockUPDataSet2
        '
        'NameTableAdapter
        '
        Me.NameTableAdapter.ClearBeforeFill = True
        '
        'DeleteButton
        '
        Me.DeleteButton.Font = New System.Drawing.Font("Microsoft Sans Serif", 10.8!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.DeleteButton.Location = New System.Drawing.Point(143, 290)
        Me.DeleteButton.Name = "DeleteButton"
        Me.DeleteButton.Size = New System.Drawing.Size(200, 57)
        Me.DeleteButton.TabIndex = 7
        Me.DeleteButton.Text = "Delete Previous Records"
        Me.DeleteButton.UseVisualStyleBackColor = True
        '
        'InputForm
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(8.0!, 16.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(562, 534)
        Me.Controls.Add(Me.InputGroupBox)
        Me.Name = "InputForm"
        Me.Text = "Scheduler Input Form"
        Me.InputGroupBox.ResumeLayout(False)
        Me.InputGroupBox.PerformLayout()
        Me.UnavailableGroupBox.ResumeLayout(False)
        Me.UnavailableGroupBox.PerformLayout()
        CType(Me.MajorProjMockUPDataSet, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.MajorProjMockUPDataSetBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.MajorProjMockUPDataSet2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.NameBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)

    End Sub
    Friend WithEvents InputGroupBox As System.Windows.Forms.GroupBox
    Friend WithEvents Label1 As System.Windows.Forms.Label

    Private Sub Label1_Click(sender As Object, e As EventArgs) Handles Label1.Click

    End Sub
    Friend WithEvents UnavailableGroupBox As System.Windows.Forms.GroupBox
    Friend WithEvents Label2 As System.Windows.Forms.Label

    Private Sub DateTimePicker1_ValueChanged(sender As Object, e As EventArgs)

    End Sub
    Friend WithEvents EndDatePicker As System.Windows.Forms.DateTimePicker
    Friend WithEvents Label3 As System.Windows.Forms.Label
    Friend WithEvents SubmitButton As System.Windows.Forms.Button
    Friend WithEvents ClinicianNameCombo As System.Windows.Forms.ComboBox
    Friend WithEvents StartDatePicker As System.Windows.Forms.DateTimePicker
    Friend WithEvents MajorProjMockUPDataSetBindingSource As System.Windows.Forms.BindingSource
    Friend WithEvents MajorProjMockUPDataSet As MajorProjectFormMockUp.MajorProjMockUPDataSet
    Friend WithEvents MajorProjMockUPDataSet2 As MajorProjectFormMockUp.MajorProjMockUPDataSet2
    Friend WithEvents NameBindingSource As System.Windows.Forms.BindingSource
    Friend WithEvents NameTableAdapter As MajorProjectFormMockUp.MajorProjMockUPDataSet2TableAdapters.NameTableAdapter
    Friend WithEvents DeleteButton As System.Windows.Forms.Button


#End Region


End Class
